# Generated by Django 2.1.1 on 2018-11-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enterPassword',
            field=models.CharField(default=110411506, max_length=50),
            preserve_default=False,
        ),
    ]
