# Generated by Django 2.1.1 on 2018-11-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181106_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
