# Generated by Django 2.1.1 on 2018-11-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cID', models.CharField(max_length=12)),
                ('cPassword', models.CharField(max_length=30)),
                ('cCurrAccID', models.CharField(max_length=30)),
            ],
        ),
    ]
