# Generated by Django 2.1.1 on 2018-11-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cCurrAccID',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
