# Generated by Django 2.1.1 on 2018-11-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20181108_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cName',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
