# Generated by Django 2.1.1 on 2018-11-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_userdata_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cName',
            field=models.CharField(max_length=10),
        ),
    ]
