# Generated by Django 2.1.1 on 2018-11-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20181110_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cName',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
