# Generated by Django 2.1.1 on 2018-11-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20181110_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_11',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_13',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_14',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_15',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_16',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_17',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_18',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_19',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_20',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cCourseUrl_9',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
