# Generated by Django 2.1.1 on 2018-11-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20181116_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_1',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_10',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_11',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_13',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_14',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_15',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_16',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_17',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_18',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_19',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_2',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_20',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_3',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_4',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_5',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_6',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_7',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_8',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cCourseUrl_9',
        ),
    ]
